CREATE TABLE IF NOT EXISTS users (
    uid INTEGER,
    user VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    hashed_password CHAR(60) NOT NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (uid)
);

CREATE TABLE IF NOT EXISTS threads (
    tid INTEGER,
    title VARCHAR(100) NOT NULL,
    aid INTEGER NOT NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (tid),
    FOREIGN KEY (aid) REFERENCES users
);

CREATE TABLE IF NOT EXISTS messages (
    mid INTEGER,
    tid INTEGER NOT NULL,
    aid INTEGER NOT NULL,
    body VARCHAR(1000) NOT NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (mid),
    FOREIGN KEY (tid) REFERENCES threads,
    FOREIGN KEY (aid) REFERENCES users
);